### ISSUE TITLE
Documentation NOS Plugin missing key word

### ISSUE THREAD

**Issue by network-shark** [fakenos/fakenos#19]
Hey ! 

I am trying to extend a driver for my needs and just copy pasted the documentation.

https://fakenos.github.io/fakenos/development/creating_nos_plugin/#create-nos-plugin-from-a-python-file
```
With this YAML file, you can register a NOS plugin like this:

hosts:
    R1:
        username: user
        password: user
        port: 6000
        nos:
            plugin: path/to/my_nos.yaml
```

If I use this I am getting an error . 

```
Initiating FakeNOS
Traceback (most recent call last):
  File "/home/myhome/venv/test/bin/fakenos", line 8, in <module>
    sys.exit(run_cli())
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/plugins/utils/cli.py", line 52, in run_cli
    fakenet = FakeNOS(inventory=args.INVENTORY)
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/fakenos.py", line 92, in __init__
    self._init()
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/fakenos.py", line 131, in _init
    self._instantiate_host_object(host_name, port, replicas, params)
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/fakenos.py", line 169, in _instantiate_host_object
    self._instantiate_single_host_object(h_name, p, params)
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/fakenos.py", line 201, in _instantiate_single_host_object
    self.hosts[host] = Host(name=host, port=port, fakenos=self, **params)
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/host.py", line 53, in __init__
    self._validate()
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/host.py", line 83, in _validate
    self._check_if_platform_is_supported(self.platform)
  File "/home/myhome/venv/test/lib64/python3.8/site-packages/fakenos/core/host.py", line 89, in _check_if_platform_is_supported
    raise ValueError(
ValueError: Platform None is not supported by FakeNOS.                     Supported platforms are: ['alcatel_aos', 'alcatel_sros', 'allied_telesis_awplus', 'arista_eos', 'aruba_os', 'avaya_ers', 'avaya_vsp', 'broadcom_icos', 'brocade_netiron', 'checkpoint_gaia', 'cisco_asa', 'cisco_ftd', 'cisco_ios', 'cisco_nxos', 'cisco_s300', 'cisco_xr', 'dell_force10', 'dlink_ds', 'eltex', 'ericsson_ipos', 'extreme_exos', 'hp_comware', 'hp_procurve', 'huawei_smartax', 'huawei_vrp', 'ipinfusion_ocnos', 'juniper_junos', 'linux', 'ubiquiti_edgerouter', 'ubiquiti_edgeswitch', 'vyatta_vyos', 'yamaha', 'zyxel_os']
```

I just fixed it by adding platform as a keyword to the yaml.

```
With this YAML file, you can register a NOS plugin like this:

hosts:
    R1:
        username: user
        password: user
        port: 6000
        platform: cisco_ios
        nos:
            plugin: path/to/my_nos.yaml
```

I will open a PR for this , if you can confirm this is the correct behavior.

**Comment by msheiny** [comment]
I just tried to reproduce this on the latest commit `b465bc2` in the `master` branch and was not able to reproduce the error locally. 

However, I do experience this error in my environment. I looked at what I installed from `pip` which is `1.0.1`. This is the latest version published to PyPI BUT the version listed in this repository is `1.1.0`. So looks like the issue is fixed in the code-base in git but not in whats been published to pypi.

**Comment by msheiny** [comment]
Argggg nevermind, this problem is still around in the latest version. I hit this error when trying to programmatically use the plugin option. I've been kicking around it for now by patching:


```
with patch.object(Host, '_check_if_platform_is_supported') as mock_platform:
            FakeNOS(inventory=fake_ios_inventory, plugins=[os.path.join(current_file_path, "fakenos/custom_ios.yaml")]).start()
```
